#!/bin/bash -eu

cd ./server

$(aws ecr get-login --registry-ids $AWS_ACCOUNT_ID --region ap-southeast-2 --no-include-email)

AWS_DOCKER_REGISTRY=$AWS_ACCOUNT_ID.dkr.ecr.ap-southeast-2.amazonaws.com

BASE_NAME="docker-server"
LOCAL_IMAGE_NAME="docker-exec"/$BASE_NAME
VERSION=$(TZ=Australia/Melbourne date +'%Y%m%d%H%M')

REMOTE_IMAGE_NAME=$AWS_DOCKER_REGISTRY/$LOCAL_IMAGE_NAME

tag_push_image() {
  docker tag $LOCAL_IMAGE_NAME $1:$VERSION
  docker push $1:$VERSION
}

docker-compose --project-name $BASE_NAME run --rm gradle gradle clean bootJar

docker build -t $LOCAL_IMAGE_NAME .

tag_push_image $REMOTE_IMAGE_NAME
